### ISSUE TITLE
Line annotation length output

### ISSUE THREAD

**Issue by BGWoodward** [BGWoodward/FishAnnotator#23]
For use cases where a line annotation is being drawn, this usually corresponds to a length measurement. This measurement should be output to the csv file as an extra column for that annotation

**Comment by jrtcppv** [comment]
I think this should be done via post-processing (python).  The csv file is a "track level" file, so I might compose a track of all line annotations, and then what is the right answer?  The average?  I could also have a track composed of all boxes, some lines and some dots, etc. so it wouldn't make sense to dump out line length in the csv file.

**Comment by jrtcppv** [comment]
Resolution is to write csv files alongside json for the image annotator only.
