### ISSUE TITLE
Image Annotator change annotation type

### ISSUE THREAD

**Issue by BGWoodward** [BGWoodward/FishAnnotator#31]
Currently in the list of annotations, it is not possible to change the type and sub-type of an existing annotation.

**Comment by jrtcppv** [comment]
This is not a bug, users could just recreate the annotation

**Comment by BGWoodward** [comment]
This is a bug. That is not a feasible workflow for users reviewing machine made annotations. Having them have to delete and then remake an annotation is not a good workflow. Letting them correct labels on correctly drawn boxes is a good workflow.

**Comment by jrtcppv** [comment]
A bug is when things are not working as intended, I intended it to work that way when I coded the app.  Therefore it's an enhancement.

**Comment by BGWoodward** [comment]
fair enough, I thought it was a bug because the video annotator doesn't work that way.

**Comment by jrtcppv** [comment]
maybe we should just use this for chat instead of skype

**Comment by BGWoodward** [comment]
that seems like a bad idea

**Comment by jrtcppv** [comment]
ya agree
