### ISSUE TITLE
Video Player differences between Windows/Linux

### ISSUE THREAD

**Issue by BGWoodward** [BGWoodward/FishAnnotator#51]
There is a difference in the frame accounting between Windows and Linux, especially on lower framerate videos. This discrepancy causes annotations loaded in Windows to look wrong on Linux. 

Further, Linux does not seem to have consistent frame accounting in general. Annotations created in a video can not accurately be seeked to using the "Go to Frame" button, both within and across sessions.

**Comment by BGWoodward** [comment]
I think this may have to do with opencv on Ubuntu possibly not having ffmpeg support

**Comment by BGWoodward** [comment]
further digging indicates the issue is with the behavior of emitprocessedimage. The mutex locker behavior seems to be inhibiting the sending of the updated frame_index_ member variable.

**Comment by jrtcppv** [comment]
ffmpeg branch closes this issue
