### ISSUE TITLE
Global State Annotations Bug

### ISSUE THREAD

**Issue by ailich** [BGWoodward/FishAnnotator#86]
Global State options do not reset when opening a new video, and instead follows the pattern seen in the last video. For example, if sponges appeared in the last video at frame 100, when I load a new video the Global Stat annotations will automatically check sponges on at frame 100.

**Comment by jrtcppv** [comment]
Should be fixed, thanks for finding that.

**Comment by ailich** [comment]
Thank you for fixing that so quickly. How do I download the updated version?

**Comment by jrtcppv** [comment]
I just uploaded a new release here:  https://github.com/BGWoodward/FishAnnotator/releases
