### ISSUE TITLE
Reloading Global State Annotations

### ISSUE THREAD

**Issue by ailich** [BGWoodward/FishAnnotator#87]
I noticed if you reload an annotation file to make changes that the fish species will still appear where you checked them the last time, but the global annotations are left blank. If you want to make changes to the global state annotations you'd have to start over, and if you want to make any changes to the fish ID's it'd result in clearing the global state annotations you had made the previous time you viewed the video as it would be overwritten by the new empty global state.

**Comment by BGWoodward** [comment]
I have confirmed this behavior, and we will look into it. Thanks for finding this, seems like it should be a not too bad fix.

**Comment by ailich** [comment]
Thank you

**Comment by BGWoodward** [comment]
Issue should be fixed. Please download the updated release (0.3.1) and let us know if it is not resolved.

**Comment by ailich** [comment]
Looks like it works to me. Thanks!
